### ISSUE TITLE
Instalation Error in Debian Stretch

### ISSUE THREAD

**Issue by jpescola** [astrada/google-drive-ocamlfuse#445]
`sudo  add-apt-repository ppa:alessandro-strada/ppa`

Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1253, in connect
    super().connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 694, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Nome ou serviço desconhecido

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 102, in _get_https_content_py3
    lp_page = urllib.request.urlopen(request, cafile=LAUNCHPAD_PPA_CERT)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Nome ou serviço desconhecido>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 327, in get_ppa_info
    ret = get_ppa_info_from_lp(user, ppa)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 92, in get_ppa_info_from_lp
    return get_info_from_lp(lp_url)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 88, in get_info_from_lp
    return _get_https_content_py3(lp_url)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 108, in _get_https_content_py3
    raise PPAException("Error reading %s: %s" % (lp_url, reason), e)
softwareproperties.ppa.PPAException: 'Error reading https://launchpad.net/api/1.0/~alessandro-strada/+archive/ubuntu/ppa: [Errno -2] Nome ou serviço desconhecido'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 393, in shortcut_handler
    return PPAShortcutHandler(shortcut)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 356, in __init__
    info = get_ppa_info(self.shortcut)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 339, in get_ppa_info
    _get_suggested_ppa_message(user, ppa))
softwareproperties.shortcuts.ShortcutException: Cannot add PPA: 'ppa:~alessandro-strada/ubuntu/ppa'.
The user named '~alessandro-strada' has no PPA named 'ubuntu/ppa'
Please choose from the following available PPAs:
 * 'google-drive-ocamlfuse-beta':  google-drive-ocamlfuse-beta
 * 'ppa':  google-drive-ocamlfuse
Error: 'ppa:alessandro-strada/ppa' invalid
`

**Comment by astrada** [comment]
The PPA is for Ubuntu. I don't think you can use it on a Debian.

**Comment by jpescola** [comment]
I'm just following the installation manual: 
https://github.com/astrada/google-drive-ocamlfuse/wiki/Installation

**Comment by astrada** [comment]
Sorry, but I didn't try it myself. It was contributed.

**Comment by OneCDOnly** [comment]
Hi @jpescola. 

I installed 'google-drive-ocamlfuse' only recently on Debian Stretch. I've just finished retesting the process. Hope this helps: 
https://gist.github.com/OneCDOnly/972755c5c5825ddd819cb2729a52b646

**Comment by marinoborges** [comment]
I installed successfully through these steps:
root@gdrivefuse:~# apt-get update
root@gdrivefuse:~# apt-get upgrade #version debian 9.4
root@gdrivefuse:~# apt install opam software-properties-common dirmngr libcurl4-gnutls-dev libfuse-dev libgmp-dev libsqlite3-dev m4 pkg-config zlib1g-dev fuse
root@gdrivefuse:~# useradd -m -s "/bin/bash" gdrive-backup
root@gdrivefuse:~# sudo gdrive-backup
gdrive-backup@gdrivefuse:~$ opam init
gdrive-backup@gdrivefuse:~$ eval `opam config env`
gdrive-backup@gdrivefuse:~$ . /home/gdrive-backup/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true
gdrive-backup@gdrivefuse:~$ opam update
gdrive-backup@gdrivefuse:~$ opam install depext
gdrive-backup@gdrivefuse:~$ opam depext google-drive-ocamlfuse
gdrive-backup@gdrivefuse:~$ opam install google-drive-ocamlfuse

**Comment by taozitaozi** [comment]
@jpescola Thanks, according to your method succeeded.
