### ISSUE TITLE
apt instructions not applicable on a new GCE VM

### ISSUE THREAD

**Issue by rserling** [astrada/google-drive-ocamlfuse#878]
Debian 6.1.94-1 (2024-06-21) x86_64 GNU/Linux

Relevant session events:
```
$ sudo: add-apt-repository: command not found 
$ sudo apt install software-properties-common
$ sudo add-apt-repository ppa:alessandro-strada/ppa
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 362, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/bin/add-apt-repository", line 345, in main
    shortcut = handler(source, **shortcut_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
    return handler(shortcut, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 86, in __init__
    if self.lpppa.publish_debug_symbols:
       ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 126, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
                  ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 113, in lpteam
    self._lpteam = self.lp.people(self.teamname)
                   ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'people'

```
To summarize:

- the poorly-named (not yer fault) command **add-apt-repository** is not present by default (hoping deprecation)
- when added from the default provided repo, the command gets a naked syntax error

**Comment by rserling** [comment]
BTW this looks like a good solution generally and I appreciate the work, thank you. Sorry it was a fail for me. Going to try circling a different drain now.

**Comment by Elimiriel** [comment]
The same issue on Kali(using as easy GUI replacement for Ubuntu in WSL...)
